platform :ios, '15.0'

target 'AirFloat' do
  use_frameworks!

  pod 'MediaPipeTasksVision'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      end
    end
    aggregate_target.user_project.save
  end

  Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', 'Pods-AirFloat', '*.xcconfig')).each do |xcconfig_path|
    xcconfig = File.read(xcconfig_path)
    xcconfig = xcconfig.gsub('-l"MediaPipeTasksCommon"', '-framework "MediaPipeTasksCommon"')
    xcconfig = xcconfig.gsub('-l"MediaPipeTasksVision"', '-framework "MediaPipeTasksVision"')
    xcconfig = xcconfig.gsub(
      'FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/MediaPipeTasksCommon/frameworks" "${PODS_ROOT}/MediaPipeTasksVision/frameworks"',
      'FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/MediaPipeTasksCommon/frameworks" "${PODS_ROOT}/MediaPipeTasksVision/frameworks" "${PODS_XCFRAMEWORKS_BUILD_DIR}/MediaPipeTasksCommon" "${PODS_XCFRAMEWORKS_BUILD_DIR}/MediaPipeTasksVision"'
    )
    File.write(xcconfig_path, xcconfig)
  end
end
